at:
  outputs:
    dev:
      dataset: dbt_stage # dataset in bigquery to hold data loaded from dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west2
      method: oauth
      priority: interactive
      project: analytic-engineering-405716
      threads: 1
      type: bigquery
  target: dev
