at:
  outputs:
    dev:
      dataset: my_dbt # my_dbt will be appended with model schema name in BigQuery 
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west2
      method: oauth
      priority: interactive
      project: analytic-engineering-405716
      threads: 1
      type: bigquery
  target: dev
